"""initial app schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 08:46:53.401877
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_attempts_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_attempts_key'), ['key'], unique=False)

    op.create_table('bans',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('embeds',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=2048), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('fanboards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ref')
    )
    op.create_table('media',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_key', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_owner_key'), ['owner_key'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('reporter_key', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'reporter_key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('handle', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('votes',
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('voter_key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('target_type', 'target_id', 'voter_key')
    )
    op.create_table('claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('entity_ref', sa.String(length=255), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('doc_keys', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=32), nullable=True),
    sa.Column('review_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('docs_purged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_user_id'), ['user_id'], unique=False)

    op.create_table('fanboard_mods',
    sa.Column('fanboard_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['fanboard_id'], ['fanboards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fanboard_id', 'user_id')
    )
    op.create_table('follows',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_ref', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'target_type', 'target_ref')
    )
    op.create_table('lists',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_user_id'), ['user_id'], unique=False)

    op.create_table('plan_grants',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('granted_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plan')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fanboard_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('anon_nick', sa.String(length=40), nullable=True),
    sa.Column('anon_pw_hash', sa.String(length=255), nullable=True),
    sa.Column('ip_prefix', sa.String(length=20), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('voter_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('up', sa.Integer(), nullable=False),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('is_concept', sa.Boolean(), nullable=False),
    sa.Column('is_notice', sa.Boolean(), nullable=False),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fanboard_id'], ['fanboards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_fanboard_id'), ['fanboard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_voter_key'), ['voter_key'], unique=False)

    op.create_table('ratings',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title_key', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'title_key')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_title_key'), ['title_key'], unique=False)

    op.create_table('scout_events',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title_key', sa.String(length=255), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=False),
    sa.Column('rising_at', sa.DateTime(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'title_key')
    )
    op.create_table('wishlist_votes',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title_key', sa.String(length=255), nullable=False),
    sa.Column('medium', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'title_key', 'medium')
    )
    with op.batch_alter_table('wishlist_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_votes_title_key'), ['title_key'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('anon_nick', sa.String(length=40), nullable=True),
    sa.Column('anon_pw_hash', sa.String(length=255), nullable=True),
    sa.Column('ip_prefix', sa.String(length=20), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('voter_key', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('up', sa.Integer(), nullable=False),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_voter_key'), ['voter_key'], unique=False)

    op.create_table('list_items',
    sa.Column('list_id', sa.String(length=32), nullable=False),
    sa.Column('title_key', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'title_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_items')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_voter_key'))
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))

    op.drop_table('comments')
    with op.batch_alter_table('wishlist_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_votes_title_key'))

    op.drop_table('wishlist_votes')
    op.drop_table('scout_events')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_title_key'))

    op.drop_table('ratings')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_voter_key'))
        batch_op.drop_index(batch_op.f('ix_posts_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_posts_fanboard_id'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))

    op.drop_table('posts')
    op.drop_table('plan_grants')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_user_id'))

    op.drop_table('lists')
    op.drop_table('follows')
    op.drop_table('fanboard_mods')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_user_id'))

    op.drop_table('claims')
    op.drop_table('votes')
    op.drop_table('users')
    op.drop_table('reports')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_owner_key'))
        batch_op.drop_index(batch_op.f('ix_media_created_at'))

    op.drop_table('media')
    op.drop_table('fanboards')
    op.drop_table('embeds')
    op.drop_table('bans')
    with op.batch_alter_table('auth_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_attempts_key'))
        batch_op.drop_index(batch_op.f('ix_auth_attempts_at'))

    op.drop_table('auth_attempts')
    # ### end Alembic commands ###
